os: Visual Studio 2019
version: 3.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

artifacts:
  - path: artifacts

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
